
window.transEB1 = ["1. Month April: Startup capital injection by Susan and Jamey of R500 000 and R200 000 repectively. Susan owns 50% of the business and Jamey 20%, while the other shares are kept for future use.<br> In the statement of financial position, we observe why the statement 'balances' after entering the two amounts. The two amounts must be entered as two seperate transactions, to show who contributed the money. The money in the bank i.e. the R700 000, is the same money as the two capital accounts or payments of Susan and Jamey. This way, the assets = owners' equity + zero liability. Liabilities refer to payable amounts, such as debt and loans.",
"2. Property bought for a Manufacturing Facility in the local Industrial Park. The purchace price is R300 000 with no transfer cost (See Notes: Zero-rating; Vat would normally be included in the amount, and may be claimed as input VAT expense. In this case, the sale was Zero-rated and no VAT is paid).<br>The property is partly financed using own money and a mortgage of R220 000 (20-year term, 11% interest rate). Enter the R80 000 first, using money from the bank, and then a second transaction for the R220 000 loan.",
"3. Raw Material Purchase from XYZ Materials Inc. on the Invoice Number: 00123 is paid and delivered. Quantity: 1000 units of steel, 500 units of plastic, 200 units of electronic components at a cost of R10 000 + R2 500 + R4 000 for each portion. All amounts include VAT at 15%. For accounting purposes, all raw materials are allocated to the same account, but keep the amounts as seperate transactions inclusive of the VAT. In some companies, the raw material may be split into RM-Steel, RM-Plastic etc. After completing the three transactions, transfer the VAT paid from the RM account to the Input VAT account. The company does not own this asset, they are just custodians for the VAT and will pay the VAT to the Government each month.",
"4. Asset nr. 0001 is bought: Machinery and Equipment at a purchase Price of R150 000. The useful Life is 10 years, and depreciation method is Straight-line. The salvage value is expected to be R20 000. VAT of 15% is included and may be shown as an expense (see Notes). Similar to the raw material, in some companies accounts may be more detailed and each big machine may have its own account. Here we lump machines and equipment together to simplify our accounts. In this case, make two seperate transactions, one to pay the Machine excluding VAT and the second transaction to pay the VAT and debit the Input VAT account. Both this method and the previous (on the raw material) give the same final result in the statements.",
"5. Work in progress (WIP) in the factory receives raw materials of Steel(800 units), Plastic(400 units) and Electronic Components(200 units).  Do seperate transactions for each type of raw material to allow management to track the inventory. They use R5 000 to pay labor and R3000.09 for direct overhead to manufacture components in WIP. Lump the labor and overhead together in one transaction and Debit it to the WIP account.",
"6. 200 Gizmos in Trade inventory (result of all previous labor and overheads) are recieved from WIP. Each Gizmo contains 4 steel units, 2 plastic units and one electronic component. Since the Gizmos are now the inventory item, we need to calculate a value per Gismo to use when we sell them. In this case, the complete value of WIP is transferred as one transaction of R20 174.00. Each Gizmo is valued at R100.87.",
"7. Sales Revenue is received in cash from Acme Corporation for Sales Order Number: 56789. Quantity Sold is 120 Gizmos at a Sales Price of R500 per unit, VAT excl. Total Sales Revenue is R69000 inclusive of VAT. Enter this as Sales or Revenues of R60 000 and a second transaction of R9000 VAT payable. Though Susan's company receives the VAT, they are just custodians of the money (or agents of the tax system). The VAT never belongs to them.",
"8. Raw Material Purchase from XYZ Materials Inc. on the Invoice Number: 00123 is delivered but not yet paid. Quantity: 2000 units of steel, 900 units of plastic, 300 units of electronic components at a cost of R20 000 + R4 500 + R6 000 for each portion. All amounts include VAT at 15%. For accounting purposes, all raw materials are allocated to the same account. In some companies, the raw material may be split into RM-Steel, RM-Plastic etc. Do three seperate transactions for the different materials including the VAT, and then a fourth transaction to move the VAT value from Raw Materials to Input VAT. This is VAT that the company has already paid to goverment as a tax, and may be shown as an expense for the company. At the end of the month, the company may claim their Input VAT expenses to reduce the amount of Income Tax payable.",
"9. Work in progress (WIP) in the factory receives raw materials of Steel(1600 units), Plastic(800 units) and Electronic Components(300 units). Remember to enter 3 seperate transactions to allow management to track the material movements. They use R12 000 to pay labor and R5000 for direct overhead, which is entered as a single transation.",
"10. 250 Gizmos in Trade inventory (result of all previous labor and overheads) are recieved from WIP. Each Gizmo contains 4 steel units, 2 plastic units and one electronic component.",
"11. Gizmos are delivered to Acme Corporation for Sales Order Number: 56791. Quantity Sold is 220 Gizmos at a Sales Price of R500 per unit, Vat excl. Total Sales Revenue is R126500 inclusive of VAT but is not yet paid",
"13. Susan enters the transactions for the loan repayment for the month. Do the Capital repayment first and the interest portion as a second transaction. Click the Loan button top left.",
"12. Monthly Depreciation is calculated on asset 0001 for one month and entered into the system. Reminders: Purchase Price of R150 000. Useful Life is 10 years, and depreciation method is Straight-line. Salvage value is expected to be R20 000. VAT of 15% was included. Click the Depreciation button top left.",
"13. Create a single transaction to pay the balance of VAT and a second transaction to pay 40% of the outstanding accounts i.e. Accounts Payable.",
"14. Acme Corporation pays 60% of their account for Sales Order Number: 56791. The Total Sales Revenue was R126500 inclusive of VAT.",
"15. Calculate the Profit before tax, keeping in mind that VAT of 15% are included on all sales amounts.",
"16. Using the Profit before tax, calculate the tax provision for the month. Enter the Tax Expense on the Income Statement, and Credit the Tax Payable account (see Notes). That way, when you actually pay the tax to SARS, You just Debit the Tax Payable account and Credit your Bank account. The provision or payable accounts are estimates for what must be paid EOFY. Do not yet pay the tax until it is due at the End of the Financial Year (EOFY). In South Africa, the end of the finacial year is 28 February 2025."];

var DebitCorr=['Bank','Bank','Land and Buildings','Land and Buildings','Raw Material','Raw Material','Raw Material','Input VAT','Machinery Vehicles and Equipment','Input VAT','WIP Inventory','WIP Inventory','WIP Inventory','WIP Inventory','Merchandise+Trade inventory','Bank','Bank','COGS','Raw Material','Raw Material','Raw Material','Input VAT','WIP Inventory','WIP Inventory','WIP Inventory','WIP Inventory','Merchandise+Trade inventory','Accounts Receivable','Accounts Receivable','Long term loans','Interest paid','Depreciation','Accounts Payable','Vat Payable','Other Expenses','Bank','Bank','Tax'];//accounts correct in order????

var CreditCorr=['Susan','Jamey','Bank','Long term loans','Bank','Bank','Bank','Raw Material','Bank','Bank','Raw Material','Raw Material','Raw Material','Bank','WIP Inventory','Sales or Revenues','Vat Payable','Merchandise+Trade inventory','Accounts Payable','Accounts Payable','Accounts Payable','Raw Material','Raw Material','Raw Material','Raw Material','Bank','WIP Inventory','Sales or Revenues','Vat Payable','Bank','Bank','Machinery Vehicles and Equipment','Bank','Input VAT','Vat Payable','Accounts Receivable','Accounts Receivable','Tax Payable'];

var AmountCorr=[50000000,20000000,30000000,22000000,1000000,250000,400000,215217,13043478,1956522,695652,173913,347826,800009,2017400,6000000,900000,1210440,2000000,450000,600000,397826,1391304,347826,521739,1700000,3221739,11000000,1650000,25415,201667,92029,1220000,2569565,19565,6600000,990000,4338499];
/*,Sales Revenue:
Customer: Acme Corporation,Sales Order Number: 56789,Quantity Sold: 600 units,Sales Price: R20 per unit,Total Sales Revenue: R12 000,Month 3: March
Raw Material Purchase:
Supplier: DEF Components Ltd.,Invoice Number: 04567,Quantity: 1200 units of plastic, 300 units of electronic components,Total Cost: R6 000,WIP Inventory:
Raw Materials Used: Plastic, Electronic Components,Quantity Used: 1000 units,Conversion Cost: R8 000,Depreciation Expense:
Asset: Machinery and Equipment,Monthly Depreciation: R1,250]*/