Susan starts a business by depositing R100 000 into a business account HotShoes. HotShoes received materials to be used in manufacturing in the amount of R40 000 incl.VAT on credit. At the end of the month, Susan takes an inventory of the materials left over and find its value is R18 000. Before the end of the month, HotShoes pays 30% of the R40 000 material invoice to the supplier. HotShoes use some materials to manufacture trade inventory valued at R80000 when the labour costs are included. Labour costs are paid weekly. Cash sales of R30 000 were done from trade inventory (shoes manufactured) valued at R10 000. Credit sales of R15 000 were done from trade inventory valued at R5 000. Assume that Susan included 15% VAT in the Sales listed above, and HotShoes pays VAT before the end of the month. Calculate the income tax of 28% that is due for the month and make provision so that your books show a more accurate expected profit. The income tax will not actually be paid until the end of the year.
window.transEB1 = ["1. Month April: Susan starts a business by depositing R100 000 into a business account HotShoes.<br> In the statement of financial position, we observe why the statement 'balances' after entering the amount. The money in the bank i.e. the R100 000, is the same money as the capital account or payment of Susan. This way, the assets = owners' equity + zero liability. Liabilities refer to payable amounts, such as debt and loans of which there is none at this time.",
"2. HotShoes received materials to be used in manufacturing in the amount of R40 000 incl.VAT on credit. We will split the amount into actual material value and Vat. Vat is kept seperately since the company does not own the Vat. Hotshoes just keeps the Vat for the government.<br>Splitting the amount, use 40 000/1.15 = 34 782.61 as Raw Material and 40 000 - (40 000/1.15) = 5 217.39 as Input VAT. This is VAT that the company has already paid to goverment as a tax, and may be shown as an expense for the company.",
"3. At the end of the month, Susan takes an inventory of the materials left over and find its value is R18 000. That means that Hotshoes used or lost (40 000/1.15)-18 000 = R16 782.61 of the raw material during the month. We are assuming the raw material was used to manufacture shoes. This means we should transfer the RM to Trade Inventory (i.e. stuff we sell).",
"4. Before the end of the month, HotShoes pay 30% of the R40 000 material invoice to the supplier.",
"5. HotShoes use some materials to manufacture trade inventory valued at R80 000 when the labour costs are included. Labour costs are paid weekly. Since we know that Trade Inventory is currently at R16 782.61, we can calculate the amount that was paid for labour as 80 000 - 16 782.61 =R63 217.39",
"6. Cash sales of R30 000 were done from trade inventory (shoes manufactured) valued at R10 000. Enter this as Sales or Revenues of R30 000/1.15 and a second transaction of R3913.04 VAT payable.<br> Though Susan's company receive the VAT, they are just custodians of the money (or agents of the tax system). The VAT never belongs to them. <br>At the end of the month, the company may claim their Input VAT expenses to reduce the amount of Vat payable.",
"7. Credit sales of R15 000 were done from trade inventory valued at R5 000. Enter this as Sales or Revenues of R15 000/1.15 and a second transaction of R1956.52 VAT payable.<br>Though Susan's company receive the VAT, they are just custodians of the money (or agents of the tax system). The VAT never belongs to them. <br>At the end of the month, the company may claim their Input VAT expenses to reduce the amount of Vat payable.",
"9. Assume that Susan included 15% VAT in the Sales listed above, and HotShoes pays VAT before the end of the month. To do this, she enters a transaction to Credit the Input Vat and Debit the Vat Payable by 5 217.39 (the Input Vat balance that we already paid!). This reduces the amount of Vat Payable to R652.17 which she then pays to the Vat office. When she does that payment, she also enters a transaction to Debit the Vat Payable to zero." ,
"10. Calculate the income tax of 28% that is due for the month and make provision so that the books show a more accurate expected profit. The income tax will not actually be paid until the end of the year."];

var DebitCorr=['Bank','Bank','Land and Buildings','Land and Buildings','Raw Material','Raw Material','Raw Material','Input VAT','Machinery Vehicles and Equipment','Input VAT','WIP Inventory','WIP Inventory','WIP Inventory','WIP Inventory','Merchandise+Trade inventory','Bank','Bank','COGS','Raw Material','Raw Material','Raw Material','Input VAT','WIP Inventory','WIP Inventory','WIP Inventory','WIP Inventory','Merchandise+Trade inventory','Accounts Receivable','Accounts Receivable','Long term loans','Interest paid','Depreciation','Accounts Payable','Vat Payable','Other Expenses','Bank','Bank','Tax'];

var CreditCorr=['Susan','Jamey','Bank','Long term loans','Bank','Bank','Bank','Raw Material','Bank','Bank','Raw Material','Raw Material','Raw Material','Bank','WIP Inventory','Sales or Revenues','Vat Payable','Merchandise+Trade inventory','Accounts Payable','Accounts Payable','Accounts Payable','Raw Material','Raw Material','Raw Material','Raw Material','Bank','WIP Inventory','Sales or Revenues','Vat Payable','Bank','Bank','Machinery Vehicles and Equipment','Bank','Input VAT','Vat Payable','Accounts Receivable','Accounts Receivable','Tax Payable'];

var AmountCorr=[50000000,20000000,30000000,22000000,1000000,250000,400000,215217,13043478,1956522,695652,173913,347826,800009,2017400,6000000,900000,1210440,2000000,450000,600000,397826,1391304,347826,521739,1700000,3221739,11000000,1650000,25415,201667,92029,1220000,2569565,19565,6600000,990000,4338499];
/*,Sales Revenue:
Customer: Acme Corporation,Sales Order Number: 56789,Quantity Sold: 600 units,Sales Price: R20 per unit,Total Sales Revenue: R12 000,Month 3: March
Raw Material Purchase:
Supplier: DEF Components Ltd.,Invoice Number: 04567,Quantity: 1200 units of plastic, 300 units of electronic components,Total Cost: R6 000,WIP Inventory:
Raw Materials Used: Plastic, Electronic Components,Quantity Used: 1000 units,Conversion Cost: R8 000,Depreciation Expense:
Asset: Machinery and Equipment,Monthly Depreciation: R1,250]*/